### ISSUE TITLE
Crash when running utern "Stage"

### ISSUE THREAD

**Issue by johandk89** [knqyf263/utern#13]
The app crashes when running utern "Stage"

Here is the full output: 

```
+ /aws/lambda/BasicRatesStage
+ /aws/lambda/CollectionCollectionAuditEventsStage
+ /aws/lambda/CollectionCollectionsStage
+ /aws/lambda/CollectionDeliveriesStage
+ /aws/lambda/CollectionDeliveryAuditEventsStage
+ /aws/lambda/CollectionNewCollectionsStage
+ /aws/lambda/CollectionNewDeliveriesStage
+ /aws/lambda/DriverNotifierProxyStage
+ /aws/lambda/GeocodeAddressStage
+ /aws/lambda/GetAddressStage
+ /aws/lambda/NotificationCheckSendShipmentStage
+ /aws/lambda/NotificationCheckSendShipmentStage › 2020/02/11/[$LATEST]a9150c83e4414a1f8bbd95b94d3c070e (2020-02-11T14:52:49+02:00)
+ /aws/lambda/NotificationSendEmailStage
+ /aws/lambda/NotificationSendOTPStage
⠹ Fetching log streams... panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14f82d6]

goroutine 1 [running]:
github.com/knqyf263/utern/cloudwatch.(*Client).ListStreams.func1(0xc000253b80, 0xc0004d0401, 0x10000c0002acd20)
	/home/travis/gopath/src/github.com/knqyf263/utern/cloudwatch/stream.go:32 +0xf6
github.com/aws/aws-sdk-go/service/cloudwatchlogs.(*CloudWatchLogs).DescribeLogStreamsPagesWithContext(0xc0000a00d8, 0x17b4da0, 0xc000079b40, 0xc0001c3170, 0xc0002c54a8, 0x0, 0x0, 0x0, 0xc0002c54c8, 0x14853f4)
	/home/travis/gopath/pkg/mod/github.com/aws/aws-sdk-go@v1.25.36/service/cloudwatchlogs/api.go:1666 +0x163
github.com/knqyf263/utern/cloudwatch.(*Client).ListStreams(0xc0001ee640, 0x17b4da0, 0xc000079b40, 0xc000366e70, 0x24, 0x170344b6810, 0x1b48838, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/knqyf263/utern/cloudwatch/stream.go:66 +0x1d2
github.com/knqyf263/utern/cloudwatch.(*Client).Tail(0xc0001ee640, 0x17b4da0, 0xc000079b40, 0xc000079b40, 0xc0001ee580)
	/home/travis/gopath/src/github.com/knqyf263/utern/cloudwatch/cloudwatch.go:100 +0x782
main.run(0xc0001e2e70, 0xc0001e2e70, 0x0)
	/home/travis/gopath/src/github.com/knqyf263/utern/main.go:121 +0x8f
main.main.func1(0xc0000c86e0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/knqyf263/utern/main.go:90 +0x8d
github.com/urfave/cli.HandleAction(0x1557380, 0x1631ed8, 0xc0000c86e0, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/github.com/urfave/cli@v1.22.1/app.go:523 +0xbe
github.com/urfave/cli.(*App).Run(0xc0001ec000, 0xc00009c020, 0x2, 0x2, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/github.com/urfave/cli@v1.22.1/app.go:285 +0x5df
main.main()
	/home/travis/gopath/src/github.com/knqyf263/utern/main.go:93 +0x907
```

Is it possible to rather specify each group instead of the app finding it with a regular expression?

**Comment by yutachaos** [comment]
This issue has been fixed at https://github.com/knqyf263/utern/pull/18.
