### ISSUE TITLE
panic: runtime error when tailing logs

### ISSUE THREAD

**Issue by pablojudd** [knqyf263/utern#16]
When running command as follows:

`utern --timestamps --no-log-stream --since 1m "/aws/lambda/testapp-demo-dev-*"`

I am ocassionally getting this:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14f82d6]

goroutine 83 [running]:
github.com/knqyf263/utern/cloudwatch.(*Client).ListStreams.func1(0xc0002bcc00, 0xc0004fae01, 0xc0005d9d30)
	/home/travis/gopath/src/github.com/knqyf263/utern/cloudwatch/stream.go:32 +0xf6
github.com/aws/aws-sdk-go/service/cloudwatchlogs.(*CloudWatchLogs).DescribeLogStreamsPagesWithContext(0xc00000e040, 0x17b4da0, 0xc0000b3b00, 0xc0005af4a0, 0xc0005d9d10, 0x0, 0x0, 0x0, 0xc0005d9eb8, 0xc000080060)
	/home/travis/gopath/pkg/mod/github.com/aws/aws-sdk-go@v1.25.36/service/cloudwatchlogs/api.go:1666 +0x163
github.com/knqyf263/utern/cloudwatch.(*Client).ListStreams(0xc00005e260, 0x17b4da0, 0xc0000b3b00, 0xc0000c40c0, 0x25, 0x1709d3001b0, 0x1b48838, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/knqyf263/utern/cloudwatch/stream.go:66 +0x1d2
github.com/knqyf263/utern/cloudwatch.(*Client).tail(0xc00005e260, 0x17b4da0, 0xc0000b3b00, 0xc0000c40c0, 0x25, 0xc00008a0c0, 0xc00001e540, 0xc00008a120, 0x0, 0x0)
	/home/travis/gopath/src/github.com/knqyf263/utern/cloudwatch/cloudwatch.go:175 +0x3b5
github.com/knqyf263/utern/cloudwatch.(*Client).Tail.func3(0xc000304620, 0xc00005e260, 0x17b4da0, 0xc0000b3b00, 0xc00008a0c0, 0xc00001e540, 0xc00008a120, 0xc0000c40c0, 0x25)
	/home/travis/gopath/src/github.com/knqyf263/utern/cloudwatch/cloudwatch.go:116 +0xd5
created by github.com/knqyf263/utern/cloudwatch.(*Client).Tail
	/home/travis/gopath/src/github.com/knqyf263/utern/cloudwatch/cloudwatch.go:114 +0x29b
```

**Comment by pablojudd** [comment]
When I run the same command after the panic, most often times it works without issue.

**Comment by pablojudd** [comment]
It seems to happen consistently with /aws/api-gateway/ logs

**Comment by pablojudd** [comment]
Mac OS x, brew install, VERSION:
   0.0.4 (rev:0bb816b8768fc8291435ced2534dd7445165358b)

**Comment by yutachaos** [comment]
This issue has been fixed at https://github.com/knqyf263/utern/pull/18.
